### ISSUE TITLE
Getting java.lang.NullPointerException when running this on 6.1.1

### ISSUE THREAD

**Issue by kumarpiyus** [mbabari/LWQWW#3]
Hello,
Tried running the lwqww.jar as the document but getting the below error.
I am able to access queueWatch via browser.

Appreciate your help on this.

LWQWW Sterling B2B Integrator activity monitoring
This code is provided to you on an "AS IS" basis, without warranty of any kind.
host: xxxxxxxxxxxxx
port: 10000
rate: 5000
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:90)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:55)
        at java.lang.reflect.Method.invoke(Method.java:508)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:58)
Caused by: java.lang.NullPointerException
        at com.ibm.de.duedorf.issupport.lwqww.main.QueueWatching.getVersion(QueueWatching.java:71)
        at com.ibm.de.duedorf.issupport.lwqww.main.QueueWatching.checkArgs(QueueWatching.java:426)
        at com.ibm.de.duedorf.issupport.lwqww.main.QueueWatching.main(QueueWatching.java:435)
        ... 5 more

**Comment by mbabari** [comment]
You are using a version that needs an /appinfo.properties file, hence the NPE: 


private void getVersion(){
      InputStream in = null;
      Properties verProps = new Properties();
      in = getClass().getResourceAsStream("/appinfo.properties");
      try {
            verProps.load(in);
            QWversion.setVERSION((String)verProps.get("program.VERSION"));
            QWversion.setCOMPANY((String)verProps.get("program.COMPANY"));
            QWversion.setCOPYRIGHT((String)verProps.get("program.COPYRIGHT"));
            QWversion.setDESCRIPTION((String)verProps.get("program.DESCRIPTION"));
            QWversion.setBUILDNUM((String)verProps.get("program.BUILDNUM"));
            QWversion.setBUILDDATE((String)verProps.get("program.BUILDDATE"));
            QWversion.setAUTHOR((String)verProps.get("program.AUTHOR"));
      } catch (IOException ex) {
            Logger.getLogger(QueueWatching.class.getName()).log(Level.SEVERE, null, ex);
      }
        System.out.println("");
        String version = QWversion.getVERSION();
      
    }    

Please create this file with the following: 

program.VERSION=210
program.COMPANY=IBM
program.COPYRIGHT=COPYRIGHT
program.DESCRIPTION=LWQWW 210
program.BUILDNUM= 2.1.0
program.BUILDDATE= APR 2019
program.AUTHOR=Support
